from .ion_channels import IonChannel

default_channels = {
    "asor": IonChannel(
        conductance=8e-5,
        channel_type='wt',
        voltage_dep='yes',
        dependence_type='voltage_and_pH',
        voltage_multiplier=1,
        nernst_multiplier=1,
        voltage_shift=0,
        flux_multiplier=1,
        allowed_primary_ion='cl',
        primary_exponent=1,
        display_name='ASOR'
    ),
    "clc": IonChannel(
        conductance=1e-7,
        channel_type='clc',
        voltage_dep='yes',
        dependence_type='voltage_and_pH',
        voltage_multiplier=1,
        nernst_multiplier=1 / 3,
        voltage_shift=0,
        flux_multiplier=2,
        allowed_primary_ion='cl',
        allowed_secondary_ion='h',
        primary_exponent=2,
        secondary_exponent=1,
        use_free_hydrogen=True,
        display_name='CLC'
    ),
    "tpc": IonChannel(
        conductance=2e-6,
        dependence_type=None,
        voltage_multiplier=-1,
        nernst_multiplier=1,
        voltage_shift=0,
        flux_multiplier=1,
        allowed_primary_ion='na',
        primary_exponent=1,
        display_name='TPC'
    ),
    "nhe": IonChannel(
        conductance=0.0,
        dependence_type=None,
        voltage_multiplier=0,
        nernst_multiplier=1,
        voltage_shift=0,
        flux_multiplier=1,
        allowed_primary_ion='na',
        allowed_secondary_ion='h',
        custom_nernst_constant=1,
        primary_exponent=1,
        secondary_exponent=1,
        use_free_hydrogen=True,
        display_name='NHE'
    ),
    "vatpase": IonChannel(
        conductance=8e-9,
        dependence_type='time',
        voltage_multiplier=1,
        nernst_multiplier=-1,
        voltage_shift=0.27,
        flux_multiplier=-1,
        allowed_primary_ion='h',
        primary_exponent=1,
        display_name='VATPase'
    ),
    "clc_h": IonChannel(
        conductance=1e-7,
        channel_type='clc',
        voltage_dep='yes',
        dependence_type='voltage_and_pH',
        voltage_multiplier=1,
        nernst_multiplier=1 / 3,
        voltage_shift=0,
        flux_multiplier=-1,
        allowed_primary_ion='cl',
        allowed_secondary_ion='h',
        primary_exponent=2,
        secondary_exponent=1,
        use_free_hydrogen=True,
        display_name='CLC_H'
    ),
    "nhe_h": IonChannel(
        conductance=0.0,
        dependence_type=None,
        voltage_multiplier=0,
        nernst_multiplier=1,
        voltage_shift=0,
        flux_multiplier=-1,
        allowed_primary_ion='na',
        allowed_secondary_ion='h',
        custom_nernst_constant=1,
        primary_exponent=1,
        secondary_exponent=1,
        use_free_hydrogen=True,
        display_name='NHE_H'
    ),
    "hleak": IonChannel(
        conductance=1.6e-8,
        dependence_type=None,
        voltage_multiplier=-1,
        nernst_multiplier=1,
        voltage_shift=0,
        flux_multiplier=1,
        allowed_primary_ion='h',
        primary_exponent=1,
        use_free_hydrogen=True,
        display_name='HLeak'
    ),
    "k_channel": IonChannel(
        conductance=0.0,
        dependence_type=None,
        voltage_multiplier=-1,
        nernst_multiplier=1,
        voltage_shift=0,
        flux_multiplier=1,
        allowed_primary_ion='k',
        primary_exponent=1,
        display_name='K'
    )
}